### ISSUE TITLE
Crash report: `TypeError: Invalid attempt to destructure non-iterable instance.In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`

### ISSUE THREAD

**Issue by 08351ty** [cowprotocol/cowswap#1933]
## URL
  
https://swap.cow.fi/#/1/limit-orders/WETH/LORDS?tab=open&page=1

## Error

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

## Stacktrace

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at r (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:1263786)
    at o (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:102477)
    at pe (https://swap.cow.fi/static/js/main.5c7bac1e.chunk.js:1:539160)
    at https://swap.cow.fi/static/js/main.5c7bac1e.chunk.js:1:1151332
    at Ls (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3971293)
    at t.unstable_runWithPriority (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3989073)
    at Ka (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3911612)
    at Ds (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3970754)
    at ys (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3962244)
    at https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3911835
    at t.unstable_runWithPriority (https://swap.cow.fi/static/js/21.f87ad9b7.chunk.js:2:3989073)
    at Ka (
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "109.0.0.0",
    "major": "109"
  },
  "engine": {
    "name": "Blink",
    "version": "109.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by elena-zh** [comment]
Hey @08351ty , could you please clarify steps you had  done before getting this error? 
Currently, I can't reproduce it: 
![image](https://user-images.githubusercontent.com/70885163/215334710-d77ed32c-a3d9-4434-9894-cf9aabf49752.png)

**Comment by elena-zh** [comment]
Duplicates #1933
