### ISSUE TITLE
Crash report: `TypeError: Invalid attempt to destructure non-iterable instance.In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`

### ISSUE THREAD

**Issue by blacktieaccountant** [cowprotocol/cowswap#2467]
## URL

https://swap.cow.fi/#/1/limit-orders/USDC/USDT?tab=open&page=1

## Error

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

## Stacktrace

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at r (https://swap.cow.fi/static/js/main.a7999048.js:2:3877412)
    at a (https://swap.cow.fi/static/js/main.a7999048.js:2:3886502)
    at A (https://swap.cow.fi/static/js/main.a7999048.js:2:1063435)
    at https://swap.cow.fi/static/js/main.a7999048.js:2:884742
    at ru (https://swap.cow.fi/static/js/main.a7999048.js:2:3351912)
    at Ac (https://swap.cow.fi/static/js/main.a7999048.js:2:3372139)
    at uc (https://swap.cow.fi/static/js/main.a7999048.js:2:3364396)
    at zi (https://swap.cow.fi/static/js/main.a7999048.js:2:3305095)
    at https://swap.cow.fi/static/js/main.a7999048.js:2:3370935
    at xc (https://swap.cow.fi/static/js/main.a7999048.js:2:3370940)
    at ic (https://swap.cow.fi/static/js/main.a7999048.js:2:3363398)
    at A (https://swap.cow.fi/static/js/main.a7999048.js:2:3588322)
    at MessagePort.P (https://swap.cow.
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "113.0.0.0",
    "major": "113"
  },
  "engine": {
    "name": "Blink",
    "version": "113.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by elena-zh** [comment]
Hey @blacktieaccountant , could you please provide a bit more details how I can reproduce this issue? 
For now, I can't reproduce it 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/b93ec3dd-cda9-4768-89d9-cd9afd51a082)

**Comment by blacktieaccountant** [comment]
Hi,
Just selected the trade pair, and the web page failed and sent that
error message with possibility to share it on github.

Luís Machado
Accounting & Finance Manager
<https://cow.fi/>
cow.fi | [image: Twitter] <https://twitter.com/CoWSwap> [image: Discord]
<https://discord.com/invite/cowprotocol> [image: Github]
<https://github.com/cowprotocol/> [image: Forum] <https://forum.cow.fi/>

**Comment by elena-zh** [comment]
Some additional details: the issue happens inside the safe, trying placing a limit order with USDC-USDT
