### ISSUE TITLE
The app is crashed when place an order to recipient in Safe

### ISSUE THREAD

**Issue by gosuto-inzasheru** [cowprotocol/cowswap#2995]
**Steps**: 
1. Open the Safe app
2. Load CoW Swap app there
3. Enable toggle Recipient
4. Place an order USDC/EURs on Mainnet to a recipient (EOA)
5. Sigh the TX

**AR**: when a TX is signed, there is a crash report
![image](https://github.com/cowprotocol/cowswap/assets/70885163/49674d56-f513-4eaa-9bfa-6ef7944fba5d)

Also, the app is crashed when open Account modal

**ER**: no crash

## URL

https://swap.cow.fi/#/1/swap/USDC/EURS

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at i (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3983312)
    at n.toFixed (https://swap.cow.fi/static/js/main.ee7755b9.js:2:2122161)
    at https://swap.cow.fi/static/js/main.ee7755b9.js:2:49145
    at s (https://swap.cow.fi/static/js/main.ee7755b9.js:2:49174)
    at I (https://swap.cow.fi/static/js/main.ee7755b9.js:2:363767)
    at Ao (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3305732)
    at Cs (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3317420)
    at Eu (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3363855)
    at bc (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3351908)
    at yc (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3351836)
    at vc (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3351699)
    at ac (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3348479)
    at ic (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3347030)
    at x (https://swap.cow.fi/static/js/main.ee7755b9.js:2:3574246)
    at MessagePor
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "115.0.0.0",
    "major": "115"
  },
  "engine": {
    "name": "Blink",
    "version": "115.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by gosuto-inzasheru** [comment]
thanks for hunting down and fixing so fast!
