### ISSUE TITLE
Crash report: `QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.`

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3809]
## URL

https://swap.cow.fi/#/11155111/widget/advanced/WETH/COW?tab=open&page=1

## Error

```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.
```

## Stacktrace

```
Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.
    at Object.setItem (https://swap.cow.fi/assets/index-nM_RxykE.js:121:15731)
    at Object.write (https://swap.cow.fi/assets/index-nM_RxykE.js:121:16626)
    at b (https://swap.cow.fi/assets/index-nM_RxykE.js:99:56627)
    at N (https://swap.cow.fi/assets/index-nM_RxykE.js:99:56495)
    at Object.write (https://swap.cow.fi/assets/index-nM_RxykE.js:936:5378)
    at b (https://swap.cow.fi/assets/index-nM_RxykE.js:99:56627)
    at Object.w [as set] (https://swap.cow.fi/assets/index-nM_RxykE.js:99:56679)
    at https://swap.cow.fi/assets/index-nM_RxykE.js:99:60081
    at https://swap.cow.fi/assets/index-HSEU_F4e.js:1:18650
    at Dx (https://swap.cow.fi/assets/index-nM_RxykE.js:677:24296)
    at lf (https://swap.cow.fi/assets/index-nM_RxykE.js:677:42451)
    at WL (https://swap.cow.fi/assets/index-nM_RxykE.js:677:36652)
    at gc (https://swap.cow.fi/assets/index-nM_RxykE.
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "120.0.0.0",
    "major": "120"
  },
  "engine": {
    "name": "Blink",
    "version": "120.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {
    "vendor": "Apple",
    "model": "Macintosh"
  },
  "cpu": {}
}
```

**Comment by anxolin** [comment]
Just more cotext on this one, I think we have an issue that makes the local storage to grow in some conditions out of control! 

https://github.com/cowprotocol/cowswap/assets/2352112/34c5d5f8-1f3b-4751-8e95-137b4af2f6e8

**Comment by elena-zh** [comment]
Hey @anxolin , could you please check it in #3831? The issue has been addressed there

**Comment by anxolin** [comment]
I can't reproduce it, neither in that PR nor before... I don't know exactly how it happenend

**Comment by anxolin** [comment]
I reproduced it now in the updated develop 
<img width="1307" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/77b8e1c9-f574-4306-b48b-01d504e860e3">

**Comment by shoom3301** [comment]
@anxolin tell me please how to reproduce it?
