### ISSUE TITLE
Crash report: `QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.`

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3945]
## URL

https://swap-dev-git-fix-3683-cowswap.vercel.app/#/11155111/advanced/WETH?tab=open&page=1

## Error

```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.
```

## Stacktrace

```
Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'twap-part-orders-list:v1' exceeded the quota.
    at Object.setItem (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:121:15731)
    at Object.write (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:121:16626)
    at b (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:99:32285)
    at D (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:99:32153)
    at Object.write (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:971:5364)
    at b (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:99:32285)
    at Object.x [as set] (https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:99:32337)
    at https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-Pllp7_0t.js:99:35739
    at https://swap-dev-git-fix-3683-cowswap.vercel.app/assets/index-0fSwCT5O.js:1
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "121.0.0.0",
    "major": "121"
  },
  "engine": {
    "name": "Blink",
    "version": "121.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {
    "vendor": "Apple",
    "model": "Macintosh"
  },
  "cpu": {}
}
```

**Comment by elena-zh** [comment]
@anxolin , can this be closed?

**Comment by anxolin** [comment]
It looks like we cant close as you found a new case today with TWAP orders with too many parts

**Comment by elena-zh** [comment]
Some more details on this issue https://cowservices.slack.com/archives/C0361CDG8GP/p1721064572672889

**Comment by rcondron** [comment]
Yep, our project's TWAP orders are hitting this error as well.
https://app.safe.global/apps/open?safe=arb1:0x151c2b49CdEC10B150B2763dF3d1C00D70C90956&appUrl=https%3A%2F%2Fswap.cow.fi

**Comment by elena-zh** [comment]
> Yep, our project's TWAP orders are hitting this error as well. https://app.safe.global/apps/open?safe=arb1:0x151c2b49CdEC10B150B2763dF3d1C00D70C90956&appUrl=https%3A%2F%2Fswap.cow.fi

Hi @rcondron , I can open your Safe and see its details without a crash. 
Could you please clear out your local storage and do a hard refresh (of does not help once, please do it twice) and let me know whether you can open your TWAP details?
