### ISSUE TITLE
App may crash when open Profile page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#485]
**The issue is not always reproducible**. Actually, I have faced it once. 
I opened the Profile page, and the app crashed: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/22a38c7c-8114-4b06-b7f1-bbc4ca699009)

**Expected**: the app is not crashed when open the Profile page

**Comment by elena-zh** [comment]
error log
```
ChunkLoadError: Loading chunk 13 failed.
(missing: https://cowswap.dev.gnosisdev.com/static/js/profile.516ca21f.chunk.js)
    at Function.i.e (https://cowswap.dev.gnosisdev.com/:1:6509)
    at https://cowswap.dev.gnosisdev.com/static/js/main.83dfd0cc.chunk.js:1:113408
    at k (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2267540)
    at Yo (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2389658)
    at Cs (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2376319)
    at ks (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2376247)
    at xs (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2376110)
    at Ps (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2373076)
    at https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2322570
    at t.unstable_runWithPriority (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2399807)
    at zi (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2322347)
    at Yi (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2322515)
    at Ji (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2322450)
    at Ie (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2393617)
    at Xt (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:2301068)
    at HTMLDivElement.i (https://cowswap.dev.gnosisdev.com/static/js/17.6a716cd9.chunk.js:2:3288242)
```

**Comment by elena-zh** [comment]
Hey @anxolin , yes, your are right. 
I have faced 2 crashes more or less at the time when a new version went live to prod. 
However, as I do not see app crashes on a daily basis, after 2 times I decided to create this issue. 
So I'm closing it. 
Thank you!
